export type AgentKey = "research" | "design" | "marketing";

export const AGENTS = {
  research: {
    key: "research" as const,
    name: "리서치",
    folder: "agents/research",
    emoji: "🔍",
    description: "시장 조사 · 사용자 리서치",
    color: {
      tab: "bg-blue-600 text-white",
      tabInactive: "text-blue-600 hover:bg-blue-50",
      activeBorder: "border-blue-600",
      badge: "bg-blue-100 text-blue-700",
      button: "bg-blue-600 hover:bg-blue-700 text-white",
      buttonOutline: "border-blue-600 text-blue-600 hover:bg-blue-50",
      bg: "bg-blue-50",
      border: "border-blue-200",
      ring: "focus:ring-blue-500",
      dot: "bg-blue-500",
      text: "text-blue-600",
    },
  },
  design: {
    key: "design" as const,
    name: "화면설계",
    folder: "agents/design",
    emoji: "🎨",
    description: "와이어프레임 · UX 설계",
    color: {
      tab: "bg-purple-600 text-white",
      tabInactive: "text-purple-600 hover:bg-purple-50",
      activeBorder: "border-purple-600",
      badge: "bg-purple-100 text-purple-700",
      button: "bg-purple-600 hover:bg-purple-700 text-white",
      buttonOutline: "border-purple-600 text-purple-600 hover:bg-purple-50",
      bg: "bg-purple-50",
      border: "border-purple-200",
      ring: "focus:ring-purple-500",
      dot: "bg-purple-500",
      text: "text-purple-600",
    },
  },
  marketing: {
    key: "marketing" as const,
    name: "마케팅",
    folder: "agents/marketing",
    emoji: "📣",
    description: "캠페인 · 콘텐츠 전략",
    color: {
      tab: "bg-orange-500 text-white",
      tabInactive: "text-orange-600 hover:bg-orange-50",
      activeBorder: "border-orange-500",
      badge: "bg-orange-100 text-orange-700",
      button: "bg-orange-500 hover:bg-orange-600 text-white",
      buttonOutline: "border-orange-500 text-orange-600 hover:bg-orange-50",
      bg: "bg-orange-50",
      border: "border-orange-200",
      ring: "focus:ring-orange-500",
      dot: "bg-orange-500",
      text: "text-orange-600",
    },
  },
} as const;
